### response without group by
#POST http://{{ngx-portal}}/parse
POST http://{{ngx-portal}}/parse?debug=1
Content-Type: application/json

< ./data2/response-without-group-by.json


### response with one group by
< {%
    request.variables.set('type', 'PieChartComponent')
    // request.variables.set('type', 'BarVerticalComponent')
%}
#POST http://{{ngx-portal}}/parse?debug=1
POST http://{{ngx-portal}}/parse
Content-Type: application/json

< ./data2/response-with-one-group-by.json


### response with two group by
< {%
    request.variables.set('type', 'BarVertical2DComponent')
%}
#POST http://{{ngx-portal}}/parse?debug=1
POST http://{{ngx-portal}}/parse
Content-Type: application/json

< ./data2/response-with-two-group-by.json

