#### healthycheck
GET http://{{ngx-portal}}/


#### e.g. AdvancedPieChartComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/AdvancedPieChartComponent.json


### e.g. AreaChartComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/AreaChartComponent.json


### e.g. AreaChartNormalizedComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/AreaChartNormalizedComponent.json


### e.g. AreaChartStackedComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/AreaChartStackedComponent.json


#### e.g. BarHorizontalComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BarHorizontalComponent.json


#### e.g. BarHorizontalNormalizedComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BarHorizontalNormalizedComponent.json


#### e.g. BarHorizontalStackedComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BarHorizontalStackedComponent.json


#### e.g. BarVerticalComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BarVerticalComponent.json


#### e.g. BarVerticalNormalizedComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BarVerticalNormalizedComponent.json


#### e.g. BarVerticalStackedComponent >> bug
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BarVerticalStackedComponent.json


### e.g. BoxChartComponent >> bug
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BoxChartComponent.json


### e.g. BubbleChartComponent >> bug
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BubbleChartComponent.json


### e.g. GaugeComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/GaugeComponent.json


### e.g. HeatMapComponent >> bug
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/HeatMapComponent.json


### e.g. LineChartComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/LineChartComponent.json


### e.g. LineChartComponent with Basis curve and autoScale
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/LineChartComponent-basis-curve.json


### e.g. NumberCardComponent >> bug
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/NumberCardComponent.json


### e.g. PieChartComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/PieChartComponent.json


### e.g. PieGridComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/PieGridComponent.json


### e.g. PolarChartComponent >> bug
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/PolarChartComponent.json


### e.g. TreeMapComponent >> bug
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/TreeMapComponent.json

